import { buildFormPanelStyles } from '../../../../ui/formPanel/formPanel.styles'
import { GRID_FORM_BUTTON_ID, GRID_FORM_FIELDS_ID, GRID_FORM_MODAL_ID, GRID_FORM_STATUS_ID } from './constants'

/**
 * Stylesheet content for the Grid advanced editor modal.
 */
export const GRID_FORM_STYLES = [
      `#${GRID_FORM_BUTTON_ID}{display:inline-flex;align-items:center;justify-content:center;gap:6px;position:relative;box-sizing:border-box;-webkit-tap-highlight-color:transparent;outline:0;margin:0;user-select:none;vertical-align:middle;appearance:none;text-decoration:none;letter-spacing:normal;box-shadow:none;font-family:"ArtifaktElement","Segoe UI",Arial,sans-serif;font-size:14px;font-weight:600;height:36px;line-height:20px;min-width:52px;padding:8px 16px;text-transform:initial;white-space:nowrap;overflow:hidden;}`,
      `#${GRID_FORM_BUTTON_ID}:disabled{opacity:.55;cursor:default;box-shadow:none;}`,
      `#${GRID_FORM_BUTTON_ID} .plm-extension-grid-advanced-editor-icon{display:inline-flex;align-items:center;justify-content:center;font-size:15px;line-height:1;}`,
      `#${GRID_FORM_MODAL_ID}{position:fixed;inset:0;z-index:2147483646;background:rgba(15,23,42,0.45);display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box;font-family:"ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-panel{position:relative;width:min(1560px,99vw);height:min(88vh,860px);max-height:94vh;background:#fff;border:1px solid #d0dbe8;border-radius:10px;box-shadow:0 16px 40px rgba(15,23,42,0.22);display:flex;flex-direction:column;overflow:hidden;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-panel.is-expanded{width:calc(100vw - 48px);height:calc(100vh - 48px);max-height:calc(100vh - 48px);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:12px 14px 8px;border-bottom:1px solid #e2e8f0;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-header-actions{display:flex;align-items:center;gap:8px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-expand{display:inline-flex;align-items:center;justify-content:center;height:30px;padding:0 10px;font:600 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-expand .zmdi{font-size:18px;line-height:1;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-title{font:700 16px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#1f2d3d;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-subtitle{margin-top:4px;font:500 12px/1.35 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#4b637a;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-loading{display:none;align-items:center;gap:8px;margin-top:6px;font:600 12px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#35516f;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-loading.is-visible{display:inline-flex;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-loading-spinner{width:14px;height:14px;border:2px solid #cbd5e1;border-top-color:#149cd8;border-radius:50%;animation:plm-extension-grid-spin .75s linear infinite;}`,
      `@keyframes plm-extension-grid-spin{to{transform:rotate(360deg)}}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-close{width:34px;height:34px;border:1px solid #cfd8e3;border-radius:8px;background:#fff;color:#334155;font:700 18px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-close:hover{background:#f8fafc;border-color:#b8c7d8;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-toolbar{display:grid;grid-template-columns:minmax(560px,1.65fr) minmax(360px,1fr);align-items:center;gap:0;padding:6px 12px;border-bottom:1px solid #e2e8f0;background:#f8fbff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-toolbar.is-fields-hidden{grid-template-columns:minmax(560px,1.65fr) minmax(360px,1fr);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-toggle{display:inline-flex;align-items:center;gap:8px;font:600 13px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#334155;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-toolbar .plm-extension-grid-form-toggle{grid-column:2;justify-self:end;margin-right:2px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-summary{grid-column:1;justify-self:start;max-width:100%;padding:0;border:0;background:transparent;color:#24486b;font:600 12px/1.3 "ArtifaktElement","Segoe UI",Arial,sans-serif;display:flex;align-items:center;gap:8px;flex-wrap:wrap;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-summary.is-ok{border:0;background:transparent;color:#24486b;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-summary.is-pending{border:0;background:transparent;color:#24486b;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-summary-label{font:700 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#24486b;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-summary-empty{font:600 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#3f5f81;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-pill-list{display:inline-flex;align-items:center;justify-content:flex-start;gap:6px;flex-wrap:wrap;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-required-pill{display:inline-flex;align-items:center;justify-content:center;max-width:220px;min-height:22px;padding:2px 8px;border:1px solid #ef9a9a;border-radius:3px;background:#fde8e8;color:#a63434;font:700 11.5px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:middle;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-toggle input{width:16px;height:16px;accent-color:#149cd8;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body{position:relative;display:grid;grid-template-columns:minmax(560px,1.65fr) minmax(360px,1fr);gap:0;flex:1;min-height:0;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body.is-fields-hidden{grid-template-columns:minmax(0,1fr);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body.is-fields-hidden .plm-extension-grid-form-main{display:none;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading{position:absolute;inset:0;z-index:6;display:none;align-items:center;justify-content:center;flex-direction:column;gap:10px;background:rgba(248,251,255,0.82);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading.is-visible{display:flex;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading .generic-loader{width:72px;text-align:center;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading .generic-loader > div{width:16px;height:16px;background-color:#149cd8;border-radius:100%;display:inline-block;animation:plm-extension-grid-bouncedelay 1.4s infinite ease-in-out both;margin:0 3px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading .generic-loader .bounce1{animation-delay:-0.32s;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading .generic-loader .bounce2{animation-delay:-0.16s;}`,
      `@keyframes plm-extension-grid-bouncedelay{0%,80%,100%{transform:scale(0)}40%{transform:scale(1)}}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-body-loading-text{color:#35516f;font:700 12px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left{display:flex;flex-direction:column;min-height:0;border-right:1px solid #e2e8f0;background:#f8fbff;overflow:hidden;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left-header{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 8px 0;position:relative;z-index:4;background:#f8fbff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left-title-tools{display:inline-flex;align-items:center;gap:8px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-selected-count{display:inline-flex;align-items:center;gap:6px;height:24px;padding:0 6px 0 8px;border:1px solid #0f84be;border-radius:999px;background:#149cd8;color:#ffffff;font:700 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-selected-count-text{display:inline-flex;align-items:center;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-selected-count-clear{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border:0;border-radius:999px;background:transparent;color:#ffffff;font:800 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;padding:0;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-selected-count-clear:hover{background:rgba(255,255,255,0.22);color:#ffffff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-selected-count-clear:disabled{opacity:.45;cursor:not-allowed;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left-actions .plm-extension-grid-form-action{height:38px;min-height:38px;padding:0 18px;font:600 14px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-left-title{font:700 12px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;letter-spacing:.05em;text-transform:uppercase;color:#44566c;padding:0;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-table-wrap{padding:8px 8px 10px;flex:1;min-height:0;overflow:hidden;position:relative;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-table-scroll{height:100%;min-height:0;overflow:auto;position:relative;isolation:isolate;background:#fff;border:1px solid #d7e3ef;border-radius:4px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font:600 12px/1.3 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#294766;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table th{position:sticky;top:0;z-index:40;background:#edf5fd;color:#3a526d;text-transform:uppercase;letter-spacing:.04em;font:700 11px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;padding:7px 16px 7px 8px;border-bottom:1px solid #d7e3ef;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-header-required-mark{color:#d12e2e;font:700 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table td{position:relative;z-index:1;padding:10px 8px;border-bottom:1px solid #e4edf6;vertical-align:middle;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:260px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table td.has-pills{white-space:normal;overflow:visible;text-overflow:clip;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr td{height:42px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table th:first-child,#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table td:first-child{width:52px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table th:first-child,#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table td:first-child{text-align:center;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-select-checkbox{-webkit-appearance:none;-moz-appearance:none;appearance:none;width:18px;height:18px;margin:0;border:1.5px solid #149cd8;border-radius:3px;background:#fff;display:inline-grid;place-content:center;vertical-align:middle;cursor:pointer;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-select-checkbox::after{content:"";width:5px;height:9px;border-right:2px solid #149cd8;border-bottom:2px solid #149cd8;transform:rotate(45deg) scale(0);transform-origin:center;transition:transform .12s ease;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-select-checkbox:checked{border-color:#149cd8;background:#fff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-select-checkbox:checked::after{transform:rotate(45deg) scale(1);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-select-checkbox:disabled{opacity:.6;cursor:not-allowed;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr{cursor:pointer;transition:background-color .12s ease,border-color .12s ease;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-active{background:#149cd8;color:#fff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-active td{border-bottom-color:rgba(255,255,255,0.28);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-staged-updated{background:#e8f6ff;color:#0b4a6f;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-removed{background:#fff1f1;color:#8a1f1f;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-removed td{text-decoration:line-through;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-staged-new{background:#eaf9ee;color:#1f5f2f;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-commit-error{background:#fff3f3;color:#8a1f1f;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table tbody tr.is-commit-error td:first-child{box-shadow:inset 3px 0 0 #d12e2e;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-row-table th.has-resize-handle{position:sticky;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-col-resizer{position:absolute;top:0;right:0;width:10px;height:100%;cursor:col-resize;user-select:none;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-col-resizer::before{content:"";position:absolute;top:4px;bottom:4px;left:4px;width:1px;background:#b7c6d8;opacity:.95;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-col-resizer:hover::before{background:#7f9dbb;}`,
      buildFormPanelStyles(`#${GRID_FORM_MODAL_ID}`, GRID_FORM_FIELDS_ID),
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 14px;border-top:1px solid #e2e8f0;background:#fff;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-stack{display:flex;flex-direction:column;align-items:flex-start;gap:7px;flex:1;min-width:520px;}`,
      `#${GRID_FORM_STATUS_ID}{min-height:18px;display:flex;align-items:center;flex-wrap:wrap;gap:8px;font:600 12px/1.3 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#4b637a;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-summary{display:inline-flex;align-items:center;gap:6px;flex-wrap:wrap;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-chip{display:inline-flex;align-items:center;justify-content:center;min-height:22px;padding:2px 8px;border-radius:4px;border:1px solid;font:700 11.5px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;white-space:nowrap;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-chip.is-new{background:#eaf9ee;border-color:#8dd7a3;color:#1f6c35;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-chip.is-edit{background:#e8f4ff;border-color:#9ecaf0;color:#1e4f7a;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-chip.is-delete{background:#fdecec;border-color:#ef9a9a;color:#9c2a2a;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-separator{color:#93a4b7;font:700 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-status-note{color:#4b637a;font:600 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-actions{display:flex;align-items:center;gap:8px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-actions-row{display:flex;align-items:center;gap:8px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-backdrop{position:absolute;inset:0;z-index:20;background:rgba(15,23,42,0.35);display:flex;align-items:center;justify-content:center;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-panel{width:min(420px,92vw);background:#fff;border:1px solid #d0dbe8;border-radius:10px;box-shadow:0 16px 40px rgba(15,23,42,0.22);padding:14px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-title{font:700 15px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#1f2d3d;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-text{margin-top:8px;font:500 13px/1.4 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#425971;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-summary{margin-top:10px;display:flex;align-items:center;flex-wrap:wrap;gap:6px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-list{margin:10px 0 0;padding-left:18px;color:#425971;font:600 12px/1.4 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-list li{margin:2px 0;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-confirm-actions{margin-top:14px;display:flex;justify-content:flex-end;gap:8px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-panel{width:min(560px,94vw);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-grid{margin-top:10px;display:flex;flex-direction:column;gap:12px;padding-top:2px;padding-bottom:2px;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-row{display:grid;grid-template-columns:84px 1fr auto;gap:12px;align-items:center;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-label{color:#2f435a;font:700 12px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;text-transform:uppercase;letter-spacing:.04em;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-track{position:relative;display:block;height:14px;border-radius:999px;background:#e2e8f0;overflow:hidden;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-fill{display:block;height:100%;width:0;background:#149cd8;transition:width .2s ease;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-progress-value{color:#4b637a;font:700 11.5px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;white-space:nowrap;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-errors-panel{width:min(680px,94vw);}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-action{display:inline-flex;align-items:center;justify-content:center;height:34px;padding:0 12px;font:600 13px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
      `#${GRID_FORM_MODAL_ID} .plm-extension-grid-form-action:disabled{opacity:.55;cursor:default;}`
].join('')


