/**
 * Shared form panel stylesheet entries.
 * Generates CSS for .plm-extension-grid-form-main, field rows, controls, and lookup styles,
 * scoped to a caller-supplied parent selector (e.g. a modal ID).
 *
 * @param parentSelector - CSS selector to scope all rules (e.g. '#my-modal')
 * @param fieldsRootId   - ID (without #) of the fields root container (e.g. 'my-fields-root')
 */
export function buildFormPanelStyles(parentSelector: string, fieldsRootId: string): string {
  return [
    `${parentSelector} .plm-extension-grid-form-main{padding:10px;overflow-y:auto;overflow-x:hidden;display:flex;flex-direction:column;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-fields-header{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:2px 0 8px;padding-bottom:8px;border-bottom:1px solid #d7e3ef;}`,
    `${parentSelector} .plm-extension-grid-form-fields-controls{display:flex;align-items:center;justify-content:flex-end;margin:0 0 8px;}`,
    `${parentSelector} .plm-extension-grid-form-fields-title{font:700 11px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;letter-spacing:.07em;text-transform:uppercase;color:#4b637a;margin:0;padding:0;border:0;}`,
    `${parentSelector} .plm-extension-grid-form-fields-close{display:inline-flex;align-items:center;justify-content:center;min-width:64px;height:30px;padding:0 10px;font:600 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-fields-note{display:none;margin:0 0 10px;padding:8px 10px;border:1px solid #c6d8ec;background:#eef6ff;border-radius:6px;}`,
    `${parentSelector} .plm-extension-grid-form-fields-note.is-visible{display:block;}`,
    `${parentSelector} .plm-extension-grid-form-fields-note-text{color:#30557c;font:600 12px/1.35 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-fields-note-required{margin-top:4px;color:#30557c;font:700 12px/1.35 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `#${fieldsRootId}{display:flex;flex-direction:column;gap:12px;overflow-x:hidden;padding:2px 2px 8px;min-width:0;width:100%;}`,
    `${parentSelector} .plm-extension-grid-form-row{display:flex;flex-direction:column;gap:6px;min-width:420px;padding:0;}`,
    `${parentSelector} .plm-extension-grid-form-label{display:flex;flex-direction:column;align-items:flex-start;gap:3px;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-label-main{display:inline-flex;align-items:center;gap:6px;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-label-text{font:700 13px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#2f435a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}`,
    `${parentSelector} .plm-extension-grid-form-label-text.is-mismatch{color:#c24141;}`,
    `${parentSelector} .plm-extension-grid-form-label-description{font:500 11.5px/1.3 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#6a7f96;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}`,
    `${parentSelector} .plm-extension-grid-form-field-error{display:none;margin-top:4px;color:#c62828;font:600 11.5px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-field-error.is-visible{display:block;}`,
    `${parentSelector} .plm-extension-grid-form-required-mark{display:inline-flex;align-items:center;justify-content:center;color:#d12e2e;font:700 16px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;line-height:1;margin-top:1px;}`,
    `${parentSelector} .plm-extension-grid-form-value{width:100%;overflow:visible;padding-top:2px;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-value > *{width:100%;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-control-wrap{position:relative;width:100%;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-control-wrap.with-prefix .plm-extension-grid-form-control{padding-left:36px;}`,
    `${parentSelector} .plm-extension-grid-form-control-prefix{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:#2f435a;font:600 14px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;pointer-events:none;}`,
    `${parentSelector} .plm-extension-grid-form-control{width:100%;height:34px;padding:0 10px;border:1px solid #cfd8e3;border-radius:6px;background:#fff;color:#111827;font:500 13px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;box-sizing:border-box;}`,
    `${parentSelector} .plm-extension-grid-form-value-clear-wrap{position:relative;display:block;width:100%;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-value-clear-wrap > .plm-extension-grid-form-control{padding-right:38px;}`,
    `${parentSelector} .plm-extension-grid-form-value-clear-wrap > .plm-extension-grid-form-control-wrap .plm-extension-grid-form-control{padding-right:38px;}`,
    `${parentSelector} .plm-extension-grid-form-value-clear{position:absolute;top:50%;right:5px;transform:translateY(-50%);min-width:24px;width:24px;height:24px;padding:0;display:inline-flex;align-items:center;justify-content:center;font:700 16px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;line-height:1;}`,
    `${parentSelector} .plm-extension-grid-form-value-clear.is-multiline{top:8px;transform:none;}`,
    `${parentSelector} .plm-extension-grid-form-control--textarea{height:88px;min-height:88px;padding:8px 10px;line-height:1.4;resize:vertical;}`,
    `${parentSelector} .plm-extension-grid-form-control--checkbox{width:18px;height:18px;margin:8px 0 0;accent-color:#149cd8;}`,
    `${parentSelector} .plm-extension-grid-form-control--select{-webkit-appearance:none;-moz-appearance:none;appearance:none;padding-right:36px;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 14 14'%3E%3Cpath d='M3 5l4 4 4-4' fill='none' stroke='%23000000' stroke-width='1.7' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 13px center;background-size:14px 14px;}`,
    `${parentSelector} .plm-extension-grid-form-control--lookup{padding-right:30px;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.has-clear .plm-extension-grid-form-control--lookup{padding-right:56px;}`,
    `${parentSelector} .plm-extension-grid-form-control[type="date"]{padding-right:8px;}`,
    `${parentSelector} .plm-extension-grid-form-control:focus{outline:none;border-color:#7cb9dd;box-shadow:0 0 0 2px rgba(31,156,220,0.12);}`,
    `${parentSelector} .plm-extension-grid-form-control:disabled{background:#f1f5f9;color:#6b7280;cursor:not-allowed;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown{width:100%;margin:0;padding:0;border:0;background:transparent;min-width:0;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown:disabled{color:#6b7280;cursor:not-allowed;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-wrap .plm-extension-grid-form-control{cursor:pointer;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-option{display:flex;align-items:center;gap:8px;padding:8px 10px;border-bottom:1px solid #e6edf5;color:#111827;font:500 13px/1.15 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-option:last-child{border-bottom:0;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-option:hover{background:#eef6ff;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-option input{width:15px;height:15px;margin:0;accent-color:#149cd8;cursor:pointer;}`,
    `${parentSelector} .plm-extension-grid-form-radio-dropdown-option input:disabled{cursor:not-allowed;}`,
    `${parentSelector} .plm-extension-grid-form-radio-loading{font:500 13px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;color:#5a7088;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap{position:relative;width:100%;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-clear{position:absolute;top:50%;right:30px;transform:translateY(-50%);display:none;align-items:center;justify-content:center;width:18px;height:18px;border:0;background:transparent;color:#5b7088;font:700 16px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;padding:0;z-index:2;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.has-value:not(.is-open) .plm-extension-grid-form-lookup-clear{display:inline-flex;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap .plm-extension-grid-form-lookup-clear:hover{color:#2f435a;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap .plm-extension-grid-form-lookup-clear:disabled{opacity:.45;cursor:not-allowed;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.is-multi{display:flex;flex-wrap:wrap;align-items:center;gap:6px;min-height:30px;padding:4px 34px 4px 8px;border:1px solid #cfd8e3;border-radius:6px;background:#fff;box-sizing:border-box;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.is-multi:focus-within{border-color:#7cb9dd;box-shadow:0 0 0 2px rgba(31,156,220,0.12);}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.is-multi .plm-extension-grid-form-control--lookup{border:0;box-shadow:none;background:transparent;height:24px;padding:0;min-width:160px;flex:1;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.is-multi .plm-extension-grid-form-control--lookup:focus{box-shadow:none;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-chips{display:flex;flex-wrap:wrap;gap:6px;align-items:center;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-chip{display:inline-flex;align-items:center;gap:6px;max-width:240px;padding:2px 8px;border-radius:4px;background:#149cd8;border:1px solid #149cd8;color:#fff;font:600 12px/1.2 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-chip-text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-chip-remove{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border:0;background:transparent;color:#fff;font:700 12px/1 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;padding:0;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-chip-remove:hover{color:#dbeafe;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap::after{content:"\\25BE";position:absolute;right:13px;top:50%;transform:translateY(-50%);font-size:14px;line-height:1;color:#000;pointer-events:none;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-wrap.is-open::after{content:"\\25B4";}`,
    `${parentSelector} .plm-extension-grid-form-lookup-menu{position:absolute;top:calc(100% + 4px);left:0;right:0;z-index:40;display:none;max-height:300px;overflow-y:auto;overflow-x:hidden;border:1px solid #b7c8dc;border-radius:8px;background:#fff;box-shadow:0 10px 24px rgba(15,23,42,0.16);}`,
    `${parentSelector} .plm-extension-grid-form-lookup-menu.is-open-up{top:auto;bottom:calc(100% + 4px);}`,
    `${parentSelector} .plm-extension-grid-form-lookup-menu.is-open{display:block;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-summary{position:sticky;top:0;z-index:1;padding:6px 10px;border-bottom:1px solid #e6edf5;background:#f7fbff;color:#35516f;font:600 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-options{display:block;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-loading{display:flex;align-items:center;gap:8px;padding:8px 10px;border-bottom:1px solid #e6edf5;color:#4f647b;font:600 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-loading-more{display:flex;align-items:center;gap:8px;padding:8px 10px;border-top:1px solid #e6edf5;background:#fff;color:#4f647b;font:600 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-spinner{width:12px;height:12px;border:2px solid #cbd5e1;border-top-color:#149cd8;border-radius:50%;animation:plm-extension-grid-spin .75s linear infinite;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-item{display:block;width:100%;padding:8px 10px;border:0;border-bottom:1px solid #e6edf5;background:#fff;color:#20364f;text-align:left;font:500 12.5px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;cursor:pointer;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-item:last-child{border-bottom:0;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-item:hover{background:#eef6ff;}`,
    `${parentSelector} .plm-extension-grid-form-lookup-empty{padding:8px 10px;color:#6b7f95;font:500 12px/1.25 "ArtifaktElement","Segoe UI",Arial,sans-serif;}`,
  ].join('')
}
